say it

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,15 +1,29 @@
 #!/usr/bin/env bash
-# Tranfers a file to a server using SSH
-if [ $# -ge 3 ]
+# Checking for command line arguemwnts
+# Tranfer a file to a server using SSH
+
+if [ $# -lt 4 ]
 then
-    if [ $# -eq 3 ]
-    then
-        # No private key provided
-        scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
-    else
-        # Private key provided
-        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
-    fi
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+fi
+
+#Assigning parameters to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+#Disabling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+#Checking if transfer was successful
+
+if [ $? -eq 0 ]
+then
+	echo "FILE was TRANSFERRED SUCCESSFULLY"
 else
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	echo "FILE was TRANSFER FAILED"
 fi
